// Generated by scripts/generate_focus_web_wire.py. DO NOT EDIT.

export const FOCUS_WEB_WIRE_VERSION = 16 as const;
export const FOCUS_WEB_RUNTIME_NOTICE_FIELD_LIMIT_BYTES = 16384 as const;

export const FOCUS_WEB_ENDPOINTS = {
  "health": {
    "method": "GET",
    "path": "/api/health",
    "pathParameters": []
  },
  "auth_bootstrap": {
    "method": "POST",
    "path": "/api/auth/bootstrap",
    "pathParameters": []
  },
  "auth_logout": {
    "method": "POST",
    "path": "/api/auth/logout",
    "pathParameters": []
  },
  "client_register": {
    "method": "POST",
    "path": "/api/client/register",
    "pathParameters": []
  },
  "meta": {
    "method": "GET",
    "path": "/api/meta",
    "pathParameters": []
  },
  "operator_status": {
    "method": "GET",
    "path": "/api/operator-status",
    "pathParameters": []
  },
  "backend_reset_preview": {
    "method": "GET",
    "path": "/api/backend-reset",
    "pathParameters": []
  },
  "backend_reset_execute": {
    "method": "POST",
    "path": "/api/backend-reset",
    "pathParameters": []
  },
  "profile": {
    "method": "POST",
    "path": "/api/profile",
    "pathParameters": []
  },
  "next_turn_settings_read": {
    "method": "GET",
    "path": "/api/settings/next-turn",
    "pathParameters": []
  },
  "next_turn_settings_update": {
    "method": "POST",
    "path": "/api/settings/next-turn",
    "pathParameters": []
  },
  "attachment_upload": {
    "method": "POST",
    "path": "/api/attachments",
    "pathParameters": []
  },
  "attachment_download": {
    "method": "GET",
    "path": "/api/attachments/{attachment_id}",
    "pathParameters": [
      "attachment_id"
    ]
  },
  "thread_list": {
    "method": "GET",
    "path": "/api/threads",
    "pathParameters": []
  },
  "thread_start": {
    "method": "POST",
    "path": "/api/threads",
    "pathParameters": []
  },
  "thread_read": {
    "method": "GET",
    "path": "/api/threads/{thread_id}",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_turns": {
    "method": "GET",
    "path": "/api/threads/{thread_id}/turns",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_summary_export": {
    "method": "GET",
    "path": "/api/threads/{thread_id}/export-summary",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_data_export": {
    "method": "GET",
    "path": "/api/threads/{thread_id}/export-data",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_tool_detail": {
    "method": "GET",
    "path": "/api/threads/{thread_id}/turns/{turn_id}/tool-items/{item_id}",
    "pathParameters": [
      "thread_id",
      "turn_id",
      "item_id"
    ]
  },
  "thread_conversation_search": {
    "method": "GET",
    "path": "/api/threads/{thread_id}/conversation-search",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_prompt": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/prompt",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_prompt_result": {
    "method": "GET",
    "path": "/api/threads/{thread_id}/prompt-result/{mutation_id}",
    "pathParameters": [
      "thread_id",
      "mutation_id"
    ]
  },
  "thread_interrupt": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/interrupt",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_unknown_mutation": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/mutation-unknown",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_rename": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/rename",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_compact": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/compact",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_review": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/review",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_goal_read": {
    "method": "GET",
    "path": "/api/threads/{thread_id}/goal",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_goal_set": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/goal",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_goal_clear": {
    "method": "DELETE",
    "path": "/api/threads/{thread_id}/goal",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_archive": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/archive",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_unarchive": {
    "method": "POST",
    "path": "/api/threads/{thread_id}/unarchive",
    "pathParameters": [
      "thread_id"
    ]
  },
  "thread_delete": {
    "method": "DELETE",
    "path": "/api/threads/{thread_id}",
    "pathParameters": [
      "thread_id"
    ]
  },
  "request_respond": {
    "method": "POST",
    "path": "/api/requests/{request_id}/respond",
    "pathParameters": [
      "request_id"
    ]
  },
  "events": {
    "method": "GET",
    "path": "/api/events",
    "pathParameters": []
  }
} as const;

export type FocusWebEndpointName = keyof typeof FOCUS_WEB_ENDPOINTS;
export type FocusWebEndpointMethod =
  (typeof FOCUS_WEB_ENDPOINTS)[FocusWebEndpointName]['method'];

export function focusWebEndpointPath(
  name: FocusWebEndpointName,
  parameters: Readonly<Record<string, string>> = {},
): string {
  const endpoint = FOCUS_WEB_ENDPOINTS[name];
  const expected = new Set<string>(endpoint.pathParameters);
  for (const key of Object.keys(parameters)) {
    if (!expected.has(key)) throw new Error(`Unexpected ${name} path parameter: ${key}`);
  }
  return endpoint.path.replace(/[{]([a-z][a-z0-9_]*)[}]/g, (_match, key: string) => {
    const value = parameters[key];
    if (!value) throw new Error(`Missing ${name} path parameter: ${key}`);
    return encodeURIComponent(value);
  });
}

export const FOCUS_WEB_ENUMS = {
  "thread_scope": [
    "current",
    "global"
  ],
  "thread_history_mode": [
    "legacy",
    "paginated",
    "unknown"
  ],
  "turn_items_view": [
    "summary",
    "full"
  ],
  "thread_tool_kind": [
    "commandExecution",
    "fileChange"
  ],
  "tool_detail_view": [
    "preview",
    "full"
  ],
  "tool_detail_scan_status": [
    "scanning",
    "found",
    "not_found"
  ],
  "warning_severity": [
    "warning",
    "error"
  ],
  "warning_attention": [
    "advisory",
    "correctness"
  ],
  "runtime_notice_method": [
    "error",
    "warning"
  ],
  "backend_reset_status": [
    "available",
    "force-only",
    "unavailable"
  ],
  "active_turn_initiator_kind": [
    "feishu",
    "web",
    "fcodex",
    "autonomous_or_unknown"
  ],
  "active_turn_setting_source": [
    "active_reroute",
    "inherited",
    "unknown"
  ],
  "lifecycle_operation": [
    "archive",
    "unarchive",
    "delete"
  ],
  "lifecycle_target_state": [
    "present",
    "archived",
    "deleted"
  ],
  "lifecycle_verification_status": [
    "already_reconciled"
  ],
  "profile_attachment_disposition": [
    "unchanged",
    "invalidated",
    "rebound"
  ],
  "selection_attachment_disposition": [
    "unchanged",
    "isolated"
  ],
  "owner_relation": [
    "none",
    "self",
    "other"
  ],
  "pending_interaction": [
    "none",
    "approval",
    "question"
  ],
  "goal_status": [
    "active",
    "paused",
    "blocked",
    "complete",
    "usageLimited",
    "budgetLimited"
  ],
  "interaction_kind": [
    "approval",
    "question",
    "elicitation"
  ],
  "interaction_action_style": [
    "primary",
    "secondary",
    "danger"
  ],
  "unknown_mutation_durability": [
    "process_local"
  ],
  "mutation_mode": [
    "started"
  ],
  "prompt_result_status": [
    "pending",
    "succeeded",
    "known_no_effect",
    "outcome_unknown"
  ],
  "prompt_result_mode": [
    "start",
    "steer"
  ],
  "mutation_action": [
    "compact",
    "review"
  ],
  "mutation_disposition": [
    "effect_observed",
    "user_discard",
    "retry_opened"
  ],
  "lifecycle_upstream_outcome": [
    "success",
    "error",
    "unknown"
  ],
  "lifecycle_cleanup": [
    "complete",
    "incomplete",
    "skipped"
  ],
  "stream_delta_kind": [
    "text",
    "thinking",
    "thinking_separator",
    "tool_output",
    "plan"
  ],
  "task_state": [
    "run",
    "done",
    "fail",
    "pending"
  ],
  "task_execution_state": [
    "active",
    "waiting_on_approval",
    "waiting_on_user_input",
    "idle",
    "not_loaded",
    "system_error",
    "completed",
    "interrupted",
    "failed",
    "unknown"
  ]
} as const;
export type FocusWebWireEnumName = keyof typeof FOCUS_WEB_ENUMS;
export type FocusWebWireEnum<Name extends FocusWebWireEnumName> =
  (typeof FOCUS_WEB_ENUMS)[Name][number];

export function isFocusWebWireEnum<Name extends FocusWebWireEnumName>(
  name: Name,
  value: unknown,
): value is FocusWebWireEnum<Name> {
  return typeof value === 'string'
    && (FOCUS_WEB_ENUMS[name] as readonly string[]).includes(value);
}

export const FOCUS_WEB_RECORDS = {
  "coordinates": {
    "typescriptType": "FocusCoordinates",
    "requiredFields": [
      "runtime_epoch",
      "revision"
    ],
    "enumFields": {}
  },
  "capability_map": {
    "typescriptType": "FocusCapabilityMap",
    "requiredFields": [
      "prompt",
      "new_thread",
      "interrupt",
      "approvals",
      "questions",
      "markdown",
      "katex",
      "mermaid",
      "file_preview",
      "terminal",
      "attachments",
      "prompt_queue",
      "durable_event_cursor",
      "bounded_history",
      "history_search",
      "tool_detail",
      "steer"
    ],
    "enumFields": {}
  },
  "reasoning_effort": {
    "typescriptType": "FocusReasoningEffort",
    "requiredFields": [
      "effort",
      "description"
    ],
    "enumFields": {}
  },
  "service_tier": {
    "typescriptType": "",
    "requiredFields": [
      "id",
      "name",
      "description"
    ],
    "enumFields": {}
  },
  "model_upgrade_info": {
    "typescriptType": "",
    "requiredFields": [
      "model",
      "upgrade_copy",
      "model_link",
      "migration_markdown"
    ],
    "enumFields": {}
  },
  "model": {
    "typescriptType": "FocusModel",
    "requiredFields": [
      "id",
      "catalog_id",
      "model",
      "display_name",
      "description",
      "is_default",
      "hidden",
      "default_reasoning_effort",
      "supported_reasoning_efforts",
      "input_modalities",
      "supports_personality",
      "service_tiers",
      "default_service_tier",
      "upgrade",
      "upgrade_info"
    ],
    "enumFields": {}
  },
  "permissions_profile": {
    "typescriptType": "",
    "requiredFields": [
      "id",
      "label"
    ],
    "enumFields": {}
  },
  "next_turn_settings": {
    "typescriptType": "FocusNextTurnSettings",
    "requiredFields": [
      "generation",
      "model",
      "reasoning_effort",
      "approval_policy",
      "permissions_profile_id"
    ],
    "enumFields": {}
  },
  "next_turn_settings_result": {
    "typescriptType": "FocusNextTurnSettingsResult",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "next_turn_settings"
    ],
    "enumFields": {}
  },
  "meta": {
    "typescriptType": "FocusMeta",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "product",
      "instance",
      "web_display_name",
      "csrf_token",
      "default_working_dir",
      "models",
      "writer_profile",
      "next_turn_settings",
      "approval_policies",
      "permissions_profiles",
      "capabilities"
    ],
    "enumFields": {}
  },
  "operator_warning": {
    "typescriptType": "FocusOperatorWarning",
    "requiredFields": [
      "code",
      "source",
      "message",
      "severity",
      "attention",
      "first_seen_at",
      "last_seen_at",
      "occurrences",
      "details"
    ],
    "enumFields": {
      "severity": "warning_severity",
      "attention": "warning_attention"
    }
  },
  "operator_status": {
    "typescriptType": "FocusOperatorStatus",
    "requiredFields": [
      "status",
      "observed_at",
      "poll_after_seconds",
      "warnings",
      "runtime_loop"
    ],
    "enumFields": {}
  },
  "runtime_error_notice_detail": {
    "typescriptType": "FocusRuntimeErrorNoticeDetail",
    "requiredFields": [
      "method",
      "message",
      "additional_details",
      "will_retry",
      "turn_id"
    ],
    "enumFields": {
      "method": "runtime_notice_method"
    }
  },
  "runtime_warning_notice_detail": {
    "typescriptType": "FocusRuntimeWarningNoticeDetail",
    "requiredFields": [
      "method",
      "message"
    ],
    "enumFields": {
      "method": "runtime_notice_method"
    }
  },
  "backend_reset_preview": {
    "typescriptType": "FocusBackendResetPreview",
    "requiredFields": [
      "instance",
      "status",
      "reason_code",
      "reason_text",
      "expected_connection_generation",
      "pending_request_count",
      "running_binding_count",
      "attached_binding_count",
      "active_loaded_thread_count",
      "loaded_thread_count",
      "runtime_verification_failed"
    ],
    "enumFields": {
      "status": "backend_reset_status"
    }
  },
  "backend_reset_result": {
    "typescriptType": "FocusBackendResetResult",
    "requiredFields": [
      "force",
      "detached_binding_count",
      "interrupted_binding_count",
      "retired_request_count",
      "purged_thread_count",
      "projection_warnings"
    ],
    "enumFields": {}
  },
  "lifecycle_verification": {
    "typescriptType": "FocusLifecycleVerification",
    "requiredFields": [
      "state",
      "verification_id"
    ],
    "enumFields": {
      "state": "lifecycle_target_state"
    }
  },
  "unknown_lifecycle_mutation": {
    "typescriptType": "FocusUnknownLifecycleMutation",
    "requiredFields": [
      "thread_id",
      "mutation_id",
      "operation"
    ],
    "enumFields": {
      "operation": "lifecycle_operation"
    }
  },
  "lifecycle_verification_result": {
    "typescriptType": "FocusLifecycleVerificationResult",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "accepted",
      "thread_id",
      "mutation_id"
    ],
    "enumFields": {
      "status": "lifecycle_verification_status",
      "operation": "lifecycle_operation"
    }
  },
  "writer_profile": {
    "typescriptType": "FocusWriterProfile",
    "requiredFields": [
      "selected_thread_id",
      "working_dir",
      "scope_generation"
    ],
    "enumFields": {}
  },
  "writer_profile_result": {
    "typescriptType": "FocusWriterProfileResult",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "writer_profile",
      "scope_changed",
      "previous_attachment_scope",
      "current_attachment_scope",
      "previous_scope_generation",
      "current_scope_generation",
      "attachment_scope_disposition",
      "invalidated_attachment_count",
      "rebound_attachment_count"
    ],
    "enumFields": {
      "attachment_scope_disposition": "profile_attachment_disposition"
    }
  },
  "thread_selection_scope": {
    "typescriptType": "FocusThreadSelectionScope",
    "requiredFields": [
      "writer_profile",
      "scope_changed",
      "previous_attachment_scope",
      "current_attachment_scope",
      "previous_scope_generation",
      "current_scope_generation",
      "attachment_scope_disposition"
    ],
    "enumFields": {
      "attachment_scope_disposition": "selection_attachment_disposition"
    }
  },
  "attachment_upload": {
    "typescriptType": "FocusAttachmentUpload",
    "requiredFields": [
      "file_id",
      "name",
      "media_type",
      "size",
      "url"
    ],
    "enumFields": {}
  },
  "owner": {
    "typescriptType": "FocusOwner",
    "requiredFields": [
      "kind",
      "holder_id",
      "relation",
      "label"
    ],
    "enumFields": {
      "relation": "owner_relation"
    }
  },
  "thread_action_capabilities": {
    "typescriptType": "FocusThreadActionCapabilities",
    "requiredFields": [
      "rename",
      "archive",
      "unarchive",
      "delete",
      "compact",
      "fork",
      "export",
      "review",
      "goal"
    ],
    "enumFields": {}
  },
  "thread_summary": {
    "typescriptType": "FocusThreadSummary",
    "requiredFields": [
      "id",
      "title",
      "name",
      "preview",
      "cwd",
      "created_at",
      "updated_at",
      "source",
      "status",
      "active_flags",
      "model_provider",
      "service_name",
      "session_id",
      "parent_thread_id",
      "can_accept_direct_input",
      "thread_source",
      "ephemeral",
      "agent_nickname",
      "agent_role",
      "subagent_kind",
      "owner",
      "pending_interaction",
      "loaded_instance",
      "loaded_state_verified",
      "observed_here",
      "selectable",
      "unavailable_reason",
      "action_capabilities",
      "history_mode"
    ],
    "enumFields": {
      "pending_interaction": "pending_interaction",
      "history_mode": "thread_history_mode"
    }
  },
  "goal_budget": {
    "typescriptType": "",
    "requiredFields": [
      "token_budget",
      "remaining_tokens",
      "turn_budget",
      "remaining_turns",
      "wall_clock_budget_ms",
      "remaining_wall_clock_ms",
      "over_budget"
    ],
    "enumFields": {}
  },
  "goal": {
    "typescriptType": "FocusGoal",
    "requiredFields": [
      "goal_id",
      "objective",
      "status",
      "tokens_used",
      "wall_clock_ms",
      "budget"
    ],
    "enumFields": {
      "status": "goal_status"
    }
  },
  "pending_request": {
    "typescriptType": "FocusPendingRequest",
    "requiredFields": [
      "id",
      "connection_generation",
      "response_capability",
      "kind",
      "method",
      "thread_id",
      "turn_id",
      "status",
      "title",
      "params",
      "owner_thread_id",
      "agent_name",
      "actions"
    ],
    "enumFields": {
      "kind": "interaction_kind"
    }
  },
  "interaction_action": {
    "typescriptType": "FocusInteractionAction",
    "requiredFields": [
      "id",
      "label",
      "style"
    ],
    "enumFields": {
      "style": "interaction_action_style"
    }
  },
  "thread_list": {
    "typescriptType": "FocusThreadList",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "scope",
      "archived",
      "limit",
      "truncated",
      "threads"
    ],
    "enumFields": {
      "scope": "thread_scope"
    }
  },
  "unknown_mutation": {
    "typescriptType": "",
    "requiredFields": [
      "mutation_id",
      "operation",
      "durability",
      "reconciling"
    ],
    "enumFields": {
      "durability": "unknown_mutation_durability"
    }
  },
  "active_turn_initiator": {
    "typescriptType": "FocusActiveTurnInitiator",
    "requiredFields": [
      "kind",
      "binding_id"
    ],
    "enumFields": {
      "kind": "active_turn_initiator_kind"
    }
  },
  "active_turn_setting": {
    "typescriptType": "FocusActiveTurnSetting",
    "requiredFields": [
      "value",
      "source"
    ],
    "enumFields": {
      "source": "active_turn_setting_source"
    }
  },
  "active_turn_settings": {
    "typescriptType": "FocusActiveTurnSettings",
    "requiredFields": [
      "model",
      "reasoning_effort",
      "approval_policy",
      "permissions_profile_id"
    ],
    "enumFields": {}
  },
  "active_turn_context": {
    "typescriptType": "FocusActiveTurnContext",
    "requiredFields": [
      "turn_id",
      "initiator",
      "feishu_audience",
      "settings"
    ],
    "enumFields": {}
  },
  "thread_snapshot": {
    "typescriptType": "FocusThreadSnapshot",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "thread",
      "turns",
      "active_turn_id",
      "active_turn_status",
      "active_turn_context",
      "pending_requests",
      "tasks",
      "older_turn_cursor",
      "has_more_turns",
      "goal",
      "token_usage",
      "token_usage_available",
      "mutation_unknown",
      "selection_scope"
    ],
    "enumFields": {}
  },
  "token_usage": {
    "typescriptType": "FocusTokenUsage",
    "requiredFields": [],
    "enumFields": {}
  },
  "token_breakdown": {
    "typescriptType": "FocusTokenBreakdown",
    "requiredFields": [],
    "enumFields": {}
  },
  "summary_prompt": {
    "typescriptType": "FocusSummaryPrompt",
    "requiredFields": [
      "id",
      "role",
      "no",
      "text",
      "title_truncated"
    ],
    "enumFields": {}
  },
  "turn_page": {
    "typescriptType": "FocusTurnPage",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "items_view",
      "page_cursor",
      "turns",
      "older_turn_cursor",
      "has_more_turns"
    ],
    "enumFields": {
      "items_view": "turn_items_view"
    }
  },
  "tool_inspection_locator": {
    "typescriptType": "FocusToolInspectionLocator",
    "requiredFields": [
      "turn_id",
      "item_id",
      "kind",
      "change_index"
    ],
    "enumFields": {
      "kind": "thread_tool_kind"
    }
  },
  "tool_detail_preview": {
    "typescriptType": "FocusThreadToolDetailPreview",
    "requiredFields": [
      "view",
      "tool"
    ],
    "enumFields": {
      "view": "tool_detail_view"
    }
  },
  "tool_detail_full": {
    "typescriptType": "FocusThreadToolDetailFull",
    "requiredFields": [
      "view",
      "source"
    ],
    "enumFields": {
      "view": "tool_detail_view"
    }
  },
  "thread_tool_detail_scan_page": {
    "typescriptType": "FocusThreadToolDetailScanPage",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "thread_id",
      "turn_id",
      "item_id",
      "kind",
      "change_index",
      "status",
      "cursor",
      "next_cursor",
      "scanned_items",
      "view",
      "detail"
    ],
    "enumFields": {
      "kind": "thread_tool_kind",
      "status": "tool_detail_scan_status",
      "view": "tool_detail_view"
    }
  },
  "conversation_search_match_range": {
    "typescriptType": "FocusConversationSearchMatchRange",
    "requiredFields": [
      "start",
      "end"
    ],
    "enumFields": {}
  },
  "conversation_search_occurrence": {
    "typescriptType": "FocusConversationSearchOccurrence",
    "requiredFields": [
      "turn_id",
      "item_id",
      "snippet",
      "snippet_match_range",
      "turn_cursor"
    ],
    "enumFields": {}
  },
  "thread_conversation_search_page": {
    "typescriptType": "FocusThreadConversationSearchPage",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "thread_id",
      "query",
      "cursor",
      "occurrences",
      "next_cursor"
    ],
    "enumFields": {}
  },
  "mutation_result": {
    "typescriptType": "FocusMutationResult",
    "requiredFields": [
      "accepted",
      "thread_id"
    ],
    "enumFields": {
      "mode": "mutation_mode",
      "action": "mutation_action",
      "disposition": "mutation_disposition"
    }
  },
  "prompt_result_receipt": {
    "typescriptType": "FocusPromptResultReceipt",
    "requiredFields": [
      "thread_id",
      "mutation_id",
      "client_user_message_id",
      "status",
      "mode",
      "turn_id",
      "reason_code"
    ],
    "enumFields": {
      "status": "prompt_result_status",
      "mode": "prompt_result_mode"
    }
  },
  "rename_result": {
    "typescriptType": "FocusRenameResult",
    "requiredFields": [
      "accepted",
      "thread_id",
      "name"
    ],
    "enumFields": {}
  },
  "goal_result": {
    "typescriptType": "FocusGoalResult",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "thread_id",
      "goal"
    ],
    "enumFields": {}
  },
  "lifecycle_result": {
    "typescriptType": "FocusLifecycleResult",
    "requiredFields": [
      "thread_id",
      "upstream_outcome",
      "focus_cleanup",
      "cleanup_errors"
    ],
    "enumFields": {
      "upstream_outcome": "lifecycle_upstream_outcome",
      "focus_cleanup": "lifecycle_cleanup"
    }
  },
  "projection_event": {
    "typescriptType": "FocusProjectionEvent",
    "requiredFields": [
      "type",
      "runtime_epoch",
      "revision"
    ],
    "enumFields": {}
  },
  "gateway_error_body": {
    "typescriptType": "FocusGatewayErrorBody",
    "requiredFields": [
      "error"
    ],
    "enumFields": {}
  },
  "document_registration": {
    "typescriptType": "FocusDocumentRegistration",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "client_id",
      "document_token",
      "document_receipt",
      "duplicate",
      "intent_generation_floor",
      "csrf_token"
    ],
    "enumFields": {}
  },
  "bootstrap_result": {
    "typescriptType": "FocusBootstrapResult",
    "requiredFields": [
      "runtime_epoch",
      "revision",
      "authenticated",
      "csrf_token",
      "expires_at"
    ],
    "enumFields": {}
  },
  "request_response_result": {
    "typescriptType": "FocusRequestResponseResult",
    "requiredFields": [
      "accepted"
    ],
    "enumFields": {}
  },
  "stream_delta": {
    "typescriptType": "FocusStreamDelta",
    "requiredFields": [
      "turn_id",
      "item_id",
      "kind",
      "delta"
    ],
    "enumFields": {
      "kind": "stream_delta_kind"
    }
  },
  "task_item": {
    "typescriptType": "",
    "requiredFields": [
      "id",
      "name",
      "kind",
      "state",
      "timing"
    ],
    "enumFields": {
      "state": "task_state"
    }
  },
  "thread_delta_detail": {
    "typescriptType": "FocusThreadDeltaDetail",
    "requiredFields": [
      "method"
    ],
    "enumFields": {}
  }
} as const;
export type FocusWebWireRecordName = keyof typeof FOCUS_WEB_RECORDS;

export function hasFocusWebRequiredFields(
  name: FocusWebWireRecordName,
  value: Readonly<Record<string, unknown>>,
): boolean {
  return FOCUS_WEB_RECORDS[name].requiredFields.every(
    (field) => Object.prototype.hasOwnProperty.call(value, field),
  );
}

export const FOCUS_WEB_EVENT_TYPES = [
  "backend_disconnected",
  "hello",
  "mutation_reconciled",
  "mutation_unknown",
  "mutation_verified",
  "owner_changed",
  "pending_request_changed",
  "profile_changed",
  "projection_invalidated",
  "runtime_changed",
  "runtime_notice",
  "settings_changed",
  "session_expired",
  "thread_delta",
  "thread_invalidated"
] as const;
export type FocusWebEventType = (typeof FOCUS_WEB_EVENT_TYPES)[number];
export const FOCUS_WEB_EVENT_TYPE_SET: ReadonlySet<string> =
  new Set<string>(FOCUS_WEB_EVENT_TYPES);

export function isFocusWebEventType(value: unknown): value is FocusWebEventType {
  return typeof value === 'string' && FOCUS_WEB_EVENT_TYPE_SET.has(value);
}

export const FOCUS_WEB_THREAD_SCOPED_EVENT_TYPES = [
  "mutation_reconciled",
  "mutation_unknown",
  "mutation_verified",
  "owner_changed",
  "pending_request_changed",
  "thread_delta",
  "thread_invalidated"
] as const;
export const FOCUS_WEB_THREAD_SCOPED_EVENT_TYPE_SET: ReadonlySet<string> =
  new Set<string>(FOCUS_WEB_THREAD_SCOPED_EVENT_TYPES);
