"""Authenticated same-origin HTTP/WebSocket gateway for Focus Web."""

from __future__ import annotations

import asyncio
import hashlib
import logging
import math
import mimetypes
import os
import pathlib
import secrets
import threading
import time
from collections.abc import AsyncIterator
from concurrent.futures import Future
from contextlib import asynccontextmanager
from dataclasses import dataclass
from typing import Any, Callable
from urllib.parse import quote

from aiohttp import WSMsgType, web

from bot import web_assets
from bot.instance_layout import DEFAULT_INSTANCE_NAME
from bot.web_runtime import gateway_request_decoder as request_decoder
from bot.backend_reset.contract import (
    BackendResetGenerationStaleError,
    BackendResetKnownNoEffectError,
    BackendResetPolicyRejectedError,
)
from bot.focus_web_wire_catalog import (
    FOCUS_WEB_ENDPOINTS,
    require_focus_web_event_type,
)
from bot.network_contract import (
    FOCUS_LOOPBACK_HOSTS,
    MIN_WEB_SESSION_TTL_SECONDS,
)
from bot.stores.web_gateway_runtime_store import WebGatewayRuntimeStore
from bot.web_runtime.auth import WebAuthManager, WebAuthSession
from bot.web_runtime.gateway_request_admission import WebGatewayRequestAdmission
from bot.web_runtime.gateway_thread_inspection import WebGatewayThreadInspectionMixin
from bot.web_runtime.gateway_external_transaction import (
    WebGatewayExternalTransactionRunner,
)
from bot.web_runtime.thread_data_export import THREAD_DATA_EXPORT_FILENAME
from bot.web_runtime.thread_summary_export import SUMMARY_EXPORT_FILENAME
from bot.web_runtime.mutation_recovery import (
    is_web_mutation_id,
)
from bot.web_runtime.projection import FocusWebProjection
from bot.web_runtime.contract import WebRuntimeError
from bot.web_runtime.update_controller import FocusUpdateError

logger = logging.getLogger(__name__)

_CLIENT_HEADER = "X-Focus-Web-Client"
_DOCUMENT_HEADER = "X-Focus-Web-Document"
_INTENT_HEADER = "X-Focus-Web-Intent"
_MAX_ATTACHMENT_BYTES = 25 * 1024 * 1024
_SAFE_INLINE_IMAGE_TYPES = {
    "image/avif",
    "image/bmp",
    "image/gif",
    "image/jpeg",
    "image/png",
    "image/webp",
    "image/x-icon",
    "image/vnd.microsoft.icon",
}
_STATIC_NO_STORE_FILENAMES = {
    "index.html",
    "THIRD_PARTY_NOTICES.html",
    "THIRD_PARTY_NOTICES.md",
    "THIRD_PARTY_SBOM.json",
}
_STOP_TIMEOUT_SECONDS = 5.0
_MAX_EXTERNAL_SESSION_SOCKETS = 8
_MAX_EXTERNAL_SOCKETS = 128
_JSON_COMPRESSION_MIN_BYTES = 16 * 1024


class WebGatewayShutdownError(RuntimeError):
    """The Gateway could not prove that its event-loop thread exited.

    ``stop()`` is deliberately retryable.  Until a later call establishes the
    thread barrier, the Gateway retains its thread, loop, and endpoint handles
    so the service lifecycle cannot mistake an incomplete stop for closure.
    """


@dataclass(slots=True, frozen=True)
class WebGatewayConfig:
    enabled: bool = True
    instance_name: str = DEFAULT_INSTANCE_NAME
    host: str = "127.0.0.1"
    port: int = 0
    session_ttl_seconds: float = 8 * 60 * 60
    session_max_lifetime_seconds: float = 7 * 24 * 60 * 60
    disconnect_grace_seconds: float = 1200.0
    event_queue_limit: int = 128
    static_dir: pathlib.Path | None = None
    trusted_proxy_origin: str = ""
    trusted_proxy_proof_sha256: str = ""


@dataclass(slots=True)
class _SocketSenderState:
    queue: asyncio.Queue[dict[str, Any]]
    task: asyncio.Task[None] | None = None
    overflowed: bool = False


@dataclass(slots=True, frozen=True)
class _ClientDocument:
    """One live browser-document incarnation for a registered Web client.

    The Gateway issues ``client_id`` and only lets its current authenticated
    session resume it during disconnect grace.  The document token does not
    survive a reload: it is generated by the Gateway and retained only by the
    current JavaScript document.  A duplicated tab may copy sessionStorage's
    resume hint, but it cannot silently share a live document's authority.
    """

    session_token: str
    incarnation_id: str
    document_token: str
    document_receipt: str


@dataclass(slots=True)
class WebGatewayPorts:
    meta: Callable[[str], dict[str, Any]]
    # Operator health is intentionally read outside RuntimeLoop.  It must stay
    # observable while that loop is the component currently delayed/stalled.
    operator_status: Callable[[], dict[str, Any]]
    backend_reset_preview: Callable[[], dict[str, Any]]
    backend_reset_execute: Callable[..., dict[str, Any]]
    update_profile: Callable[..., dict[str, Any]]
    next_turn_settings: Callable[[], dict[str, Any]]
    update_next_turn_settings: Callable[..., dict[str, Any]]
    stage_attachment: Callable[..., dict[str, Any]]
    attachment_download: Callable[[str], Any]
    prepare_list_threads: Callable[..., Any]
    prepare_read_thread: Callable[..., Any]
    prepare_list_older_turns: Callable[..., Any]
    run_prepared_thread_read: Callable[[Any], dict[str, Any]]
    abandon_prepared_thread_read: Callable[[Any], bool]
    prepare_export_thread_summary: Callable[..., Any]
    run_prepared_thread_summary_export: Callable[[Any], bytes]
    prepare_export_thread_data: Callable[..., Any]
    run_prepared_thread_data_export: Callable[[Any], bytes]
    prepare_tool_detail: Callable[..., Any]
    prepare_conversation_search: Callable[..., Any]
    start_thread: Callable[..., dict[str, Any]]
    prepare_prompt: Callable[..., Any]
    run_prepared_prompt: Callable[[Any], dict[str, Any]]
    abandon_prepared_prompt: Callable[[Any], bool]
    prompt_result: Callable[..., dict[str, Any]]
    interrupt: Callable[..., dict[str, Any]]
    resolve_unknown_mutation: Callable[..., dict[str, Any]]
    rename_thread: Callable[..., dict[str, Any]]
    compact_thread: Callable[[str, str], dict[str, Any]]
    start_review: Callable[..., dict[str, Any]]
    goal: Callable[[str, str], dict[str, Any]]
    set_goal: Callable[..., dict[str, Any]]
    clear_goal: Callable[..., dict[str, Any]]
    archive_thread: Callable[[str, str], dict[str, Any]]
    unarchive_thread: Callable[[str, str], dict[str, Any]]
    delete_thread: Callable[..., dict[str, Any]]
    respond_request: Callable[..., dict[str, Any]]
    document_intent_generation_floor: Callable[[str], int]
    client_connected: Callable[[str], None]
    client_transport_disconnected: Callable[[str], None]
    client_document_reissued: Callable[[str], None]
    client_disconnected: Callable[[str], None]
    # The update owner is optional for legacy embedders/tests that construct a
    # Gateway without the managed installer surface.
    update_status: Callable[[], dict[str, Any]] | None = None
    update_source: Callable[[str, str], dict[str, Any]] | None = None
    update_check: Callable[[str, str], dict[str, Any]] | None = None
    update_apply: Callable[[str, str], dict[str, Any]] | None = None


class WebGateway(WebGatewayThreadInspectionMixin):
    def __init__(
        self,
        *,
        config: WebGatewayConfig,
        data_dir: pathlib.Path,
        projection: FocusWebProjection,
        ports: WebGatewayPorts,
    ) -> None:
        self._config = config
        self._data_dir = pathlib.Path(data_dir)
        self._projection = projection
        self._ports = ports
        self._runtime_store = WebGatewayRuntimeStore(self._data_dir)
        self._auth = WebAuthManager(
            session_ttl_seconds=config.session_ttl_seconds,
            session_max_lifetime_seconds=config.session_max_lifetime_seconds,
            on_bootstrap_rotated=self._handle_bootstrap_rotated,
        )
        self._request_admission = WebGatewayRequestAdmission(
            auth=self._auth,
            logger=logger,
            instance_name=config.instance_name,
            trusted_proxy_origin=config.trusted_proxy_origin,
            trusted_proxy_proof_sha256=config.trusted_proxy_proof_sha256,
        )
        self._external_transactions = WebGatewayExternalTransactionRunner(
            ports.abandon_prepared_thread_read
        )
        self._prompt_transactions = WebGatewayExternalTransactionRunner(
            ports.abandon_prepared_prompt
        )
        self._thread: threading.Thread | None = None
        self._loop: asyncio.AbstractEventLoop | None = None
        self._stop_lock = threading.Lock()
        self._stop_future: Future[None] | None = None
        self._async_stop_completed = False
        self._runner: web.AppRunner | None = None
        self._ready = threading.Event()
        self._startup_error: BaseException | None = None
        self._endpoint = ""
        self._started_at = 0.0
        self._websockets: dict[str, set[web.WebSocketResponse]] = {}
        self._session_sockets: dict[str, set[web.WebSocketResponse]] = {}
        self._external_socket_reservations: dict[str, int] = {}
        self._session_clients: dict[str, set[str]] = {}
        self._client_sessions: dict[str, str] = {}
        self._client_documents: dict[str, _ClientDocument] = {}
        self._socket_clients: dict[web.WebSocketResponse, str] = {}
        self._socket_senders: dict[web.WebSocketResponse, _SocketSenderState] = {}
        self._disconnect_tasks: dict[str, asyncio.Task[None]] = {}
        self._session_expiry_tasks: dict[str, asyncio.Task[None]] = {}
        # HTTP handlers run their controller call in the default executor,
        # while WebSocket teardown is driven by this event loop.  A stale
        # controller ``connected`` snapshot must not let a writer mutation
        # overtake the last-socket transport disconnect.  All client-scoped
        # writer calls and lifecycle transitions therefore share this
        # event-loop lock.  The controller remains the authority; this lock
        # only supplies the Gateway's missing linearization point.
        self._client_operation_locks: dict[str, asyncio.Lock] = {}
        self._client_operation_lock_users: dict[str, int] = {}
        self._unsubscribe_projection: Callable[[], None] | None = None

    @property
    def endpoint(self) -> str:
        return self._endpoint

    @property
    def enabled(self) -> bool:
        return bool(self._config.enabled)

    def start(self) -> str:
        if not self.enabled:
            return ""
        if self._thread is not None and self._thread.is_alive():
            return self._endpoint
        self._validate_config()
        self._ready.clear()
        self._startup_error = None
        self._stop_future = None
        self._async_stop_completed = False
        self._thread = threading.Thread(
            target=self._thread_main, name="focus-web-gateway", daemon=True
        )
        self._thread.start()
        if not self._ready.wait(timeout=10.0):
            raise RuntimeError("Focus Web Gateway 启动超时")
        if self._startup_error is not None:
            raise RuntimeError(
                f"Focus Web Gateway 启动失败：{self._startup_error}"
            ) from self._startup_error
        return self._endpoint

    def stop(self) -> None:
        if not self.enabled:
            return
        with self._stop_lock:
            loop = self._loop
            thread = self._thread
            if thread is None:
                self._clear_runtime_store_safely()
                self._loop = None
                self._endpoint = ""
                self._stop_future = None
                self._async_stop_completed = False
                return
            if thread.is_alive() and threading.current_thread() is thread:
                raise WebGatewayShutdownError(
                    "Focus Web Gateway event-loop thread cannot prove its own shutdown barrier"
                )

            if thread.is_alive() and loop is not None and loop.is_running():
                self._await_async_stop(loop)
                try:
                    loop.call_soon_threadsafe(loop.stop)
                except Exception as exc:
                    if thread.is_alive():
                        raise WebGatewayShutdownError(
                            "Focus Web Gateway could not signal its event loop to stop; retry stop()"
                        ) from exc

            if thread.is_alive():
                thread.join(timeout=_STOP_TIMEOUT_SECONDS)
            if thread.is_alive():
                raise WebGatewayShutdownError(
                    "Focus Web Gateway event-loop thread did not exit within "
                    f"{_STOP_TIMEOUT_SECONDS:g} seconds; retry stop()"
                )

            # Only a dead producer thread is a shutdown proof.  Discovery and
            # concrete retry handles remain intact on every failure above.
            self._clear_runtime_store_safely()
            if self._thread is thread:
                self._thread = None
            if self._loop is loop:
                self._loop = None
            self._endpoint = ""
            self._stop_future = None
            self._async_stop_completed = False

    def _await_async_stop(self, loop: asyncio.AbstractEventLoop) -> None:
        if self._async_stop_completed:
            return
        future = self._stop_future
        if future is None:
            coroutine = self._stop_async()
            try:
                future = asyncio.run_coroutine_threadsafe(coroutine, loop)
            except Exception as exc:
                coroutine.close()
                raise WebGatewayShutdownError(
                    "Focus Web Gateway could not schedule async cleanup; retry stop()"
                ) from exc
            self._stop_future = future
        try:
            future.result(timeout=_STOP_TIMEOUT_SECONDS)
        except TimeoutError as exc:
            if future.done():
                # ``Future.result`` also forwards a TimeoutError raised by the
                # coroutine itself.  A settled Future is therefore an async
                # cleanup failure, not evidence that the caller merely ran
                # out of wait budget.
                try:
                    future.result(timeout=0)
                except Exception as settled_exc:
                    if self._stop_future is future:
                        self._stop_future = None
                    raise WebGatewayShutdownError(
                        "Focus Web Gateway async cleanup failed: "
                        f"{settled_exc}; retry stop()"
                    ) from settled_exc
                else:
                    self._stop_future = None
                    self._async_stop_completed = True
                    return
            # The coroutine may still complete on the Gateway loop.  Retain
            # the exact Future so a retry observes that same attempt instead
            # of racing it with a second cleanup coroutine.
            raise WebGatewayShutdownError(
                "Focus Web Gateway async cleanup did not finish within "
                f"{_STOP_TIMEOUT_SECONDS:g} seconds; retry stop()"
            ) from exc
        except Exception as exc:
            # A settled failed attempt can be replaced safely on the next
            # stop call; concrete loop/thread/endpoint ownership is retained.
            if self._stop_future is future:
                self._stop_future = None
            raise WebGatewayShutdownError(
                f"Focus Web Gateway async cleanup failed: {exc}; retry stop()"
            ) from exc
        self._stop_future = None
        self._async_stop_completed = True

    def _validate_config(self) -> None:
        host = str(self._config.host or "").strip()
        if host not in FOCUS_LOOPBACK_HOSTS:
            raise ValueError(
                "Focus Web 当前只允许监听 loopback；远程访问请使用 SSH tunnel，"
                "或让 configured trusted HTTPS proxy 转发到 loopback。"
            )
        if not 0 <= int(self._config.port) <= 65535:
            raise ValueError("web_port 必须在 0..65535 范围内")
        if self._config.trusted_proxy_origin and int(self._config.port) == 0:
            raise ValueError("trusted proxy mode 要求固定非零 web_port")
        session_ttl = float(self._config.session_ttl_seconds)
        if not math.isfinite(session_ttl) or session_ttl < MIN_WEB_SESSION_TTL_SECONDS:
            raise ValueError("web_session_ttl_seconds 必须是至少 60 秒的有限数值")
        session_max_lifetime = float(self._config.session_max_lifetime_seconds)
        if not math.isfinite(session_max_lifetime) or session_max_lifetime < MIN_WEB_SESSION_TTL_SECONDS:
            raise ValueError("web_session_max_lifetime_seconds 必须是至少 60 秒的有限数值")
        if session_max_lifetime < session_ttl:
            raise ValueError("web_session_max_lifetime_seconds 必须大于等于 web_session_ttl_seconds")
        disconnect_grace = float(self._config.disconnect_grace_seconds)
        if not math.isfinite(disconnect_grace) or disconnect_grace < 0.0:
            raise ValueError("web_disconnect_grace_seconds 必须是非负有限数值")
        if int(self._config.event_queue_limit) <= 0:
            raise ValueError("web_event_queue_limit 必须为正整数")
        static_dir = self._static_dir()
        if not (static_dir / "index.html").is_file():
            raise FileNotFoundError(
                f"未找到 Focus Web 构建产物：{static_dir / 'index.html'}；请重新执行 install.sh。"
            )

    def _thread_main(self) -> None:
        loop = asyncio.new_event_loop()
        self._loop = loop
        asyncio.set_event_loop(loop)
        try:
            loop.run_until_complete(self._start_async())
        except BaseException as exc:
            self._startup_error = exc
            if self._runner is not None:
                try:
                    loop.run_until_complete(self._runner.cleanup())
                except Exception:
                    logger.exception("回滚 Focus Web Gateway runner 失败")
                self._runner = None
            self._clear_runtime_store_safely()
            self._endpoint = ""
            self._ready.set()
            loop.close()
            return
        self._ready.set()
        try:
            loop.run_forever()
        finally:
            if self._runner is not None:
                loop.run_until_complete(self._runner.cleanup())
                self._runner = None
            self._clear_runtime_store_safely()
            self._endpoint = ""
            loop.close()

    async def _start_async(self) -> None:
        app = web.Application(
            middlewares=[
                self._request_admission.error_middleware,
                self._request_admission.security_middleware,
                self._request_admission.auth_middleware,
            ],
            client_max_size=32 * 1024 * 1024,
        )
        for endpoint in FOCUS_WEB_ENDPOINTS:
            register = getattr(app.router, f"add_{endpoint.method.lower()}")
            register(
                endpoint.path,
                getattr(self, endpoint.handler),
                name=endpoint.name,
            )
        # Keep an API typo or a stale client contract from being silently
        # served the SPA shell. This also catches a known path with the wrong
        # HTTP method after aiohttp has exhausted its method-specific route.
        app.router.add_route("*", "/api/{path:.*}", self._handle_unknown_api)
        app.router.add_get("/{path:.*}", self._handle_static)

        self._runner = web.AppRunner(app, access_log=None)
        await self._runner.setup()
        site = web.TCPSite(self._runner, str(self._config.host), int(self._config.port))
        await site.start()
        sockets = list(getattr(site, "_server", None).sockets or [])
        if not sockets:
            raise RuntimeError("Focus Web Gateway 未获得监听 socket")
        port = int(sockets[0].getsockname()[1])
        display_host = (
            "127.0.0.1" if self._config.host == "localhost" else self._config.host
        )
        if ":" in display_host and not display_host.startswith("["):
            display_host = f"[{display_host}]"
        self._endpoint = f"http://{display_host}:{port}"
        self._started_at = time.time()
        self._save_runtime()
        self._unsubscribe_projection = self._projection.subscribe(
            self._on_projection_event
        )
        logger.info("Focus Web Gateway listening on %s", self._endpoint)

    async def _stop_async(self) -> None:
        if self._unsubscribe_projection is not None:
            self._unsubscribe_projection()
            self._unsubscribe_projection = None
        for task in tuple(self._disconnect_tasks.values()):
            task.cancel()
        self._disconnect_tasks.clear()
        for task in tuple(self._session_expiry_tasks.values()):
            task.cancel()
        self._session_expiry_tasks.clear()
        clients = tuple(set(self._websockets) | set(self._client_sessions))
        sockets = [socket for group in self._websockets.values() for socket in group]
        sender_tasks = [
            state.task
            for state in self._socket_senders.values()
            if state.task is not None
        ]
        self._socket_senders.clear()
        self._websockets.clear()
        self._session_sockets.clear()
        self._external_socket_reservations.clear()
        self._session_clients.clear()
        self._client_sessions.clear()
        self._client_documents.clear()
        self._socket_clients.clear()
        self._client_operation_locks.clear()
        self._client_operation_lock_users.clear()
        for task in sender_tasks:
            task.cancel()
        for socket in sockets:
            await socket.close(code=1001, message=b"Focus service shutting down")
        for client_id in clients:
            self._ports.client_disconnected(client_id)
        if self._runner is not None:
            await self._runner.cleanup()
            self._runner = None

    @staticmethod
    def _json_response(data: Any, **kwargs: Any) -> web.Response:
        """Build a large JSON response with negotiated HTTP compression.

        A response keeps the existing JSON DTO and is compressed only after it
        crosses the threshold.  ``aiohttp`` performs the Accept-Encoding
        negotiation and writes the matching Content-Encoding/Length headers;
        the Vary header makes that representation choice cache-safe.
        """

        response = web.json_response(data, **kwargs)
        body = response.body
        if body is None or len(body) < _JSON_COMPRESSION_MIN_BYTES:
            return response
        response.enable_compression()
        vary = [value.strip() for value in response.headers.get("Vary", "").split(",")]
        if not any(value.lower() == "accept-encoding" for value in vary):
            vary.append("Accept-Encoding")
        response.headers["Vary"] = ", ".join(value for value in vary if value)
        return response

    async def _handle_health(self, _request: web.Request) -> web.Response:
        return web.json_response({"ok": True, "product": "Focus"})

    async def _handle_unknown_api(self, _request: web.Request) -> web.Response:
        return web.json_response(
            {
                "error": {
                    "code": "api_not_found",
                    "message": "Unknown Focus Web API route.",
                }
            },
            status=404,
        )

    async def _handle_bootstrap(self, request: web.Request) -> web.Response:
        self._request_admission.require_local_audience(request)
        self._request_admission.validate_origin(request, allow_missing=True)
        body = await request_decoder.decode_json_object(request)
        session = self._auth.exchange_bootstrap(str(body.get("token", "") or ""))
        if session is None:
            raise web.HTTPUnauthorized(
                text='{"error":{"code":"invalid_bootstrap","message":"Bootstrap token is invalid or already used."}}',
                content_type="application/json",
            )
        previous_session_token = self._request_admission.session_cookie_token(request)
        if previous_session_token and previous_session_token != session.session_token:
            self._auth.revoke(previous_session_token)
            await self._close_session_sockets(
                previous_session_token,
                event_type="session_expired",
                close_message=b"Focus Web session replaced",
            )
        response = web.json_response(
            {
                "authenticated": True,
                "csrf_token": session.csrf_token,
                "expires_at": session.expires_at,
                **self._projection.coordinates(),
            }
        )
        self._request_admission.set_session_cookie(response, request, session)
        return response

    async def _handle_logout(self, request: web.Request) -> web.Response:
        session = self._request_admission.session(request)
        self._auth.revoke(session.session_token)
        await self._close_session_sockets(
            session.session_token,
            event_type="session_expired",
            close_message=b"Focus Web session logged out",
        )
        response = web.json_response({"authenticated": False})
        self._request_admission.clear_session_cookie(response)
        return response

    async def _handle_client_register(self, request: web.Request) -> web.Response:
        """Register the current JavaScript document before it may act as a client.

        The resumable id is intentionally only a bounded hint.  It lets a
        reload retain the Focus writer identity only while the Gateway still
        has the same authenticated session's registration during disconnect
        grace.  A live duplicate, a different session, or a stale hint always
        receives a newly issued identity.
        """

        session = self._request_admission.session(request)
        body = await request_decoder.decode_json_object(request)
        provisional_external = (
            session.audience.kind == "external"
            and self._request_admission.session_cookie_token(request)
            != session.session_token
        )
        try:
            return await self._register_client_document_response(session, body)
        except BaseException:
            if provisional_external:
                for client_id in tuple(
                    self._session_clients.get(session.session_token, ())
                ):
                    disconnect_task = self._disconnect_tasks.pop(client_id, None)
                    if disconnect_task is not None:
                        disconnect_task.cancel()
                    if self._client_sessions.get(client_id) == session.session_token:
                        self._forget_client_session(client_id)
            raise

    async def _register_client_document_response(
        self,
        session: WebAuthSession,
        body: dict[str, Any],
    ) -> web.Response:
        claimed_client_id = request_decoder.decode_client_id_hint(
            body.get("resume_client_id", "")
        )
        incarnation_id = request_decoder.decode_document_incarnation(
            body.get("incarnation_id", "")
        )
        intent_generation_floor: int
        floor_read = False
        if claimed_client_id:
            async with self._client_operation(claimed_client_id):
                self._require_active_session(session)
                client_id, document, duplicate, reissued = (
                    self._register_client_document(
                        session,
                        claimed_client_id=claimed_client_id,
                        incarnation_id=incarnation_id,
                    )
                )
                if reissued:
                    disconnect_task = self._disconnect_tasks.pop(client_id, None)
                    if disconnect_task is not None:
                        disconnect_task.cancel()
                    try:
                        await asyncio.to_thread(
                            self._ports.client_document_reissued,
                            client_id,
                        )
                        self._require_active_session(session)
                        if self._client_documents.get(client_id) is not document:
                            raise WebRuntimeError(
                                "This browser document was replaced during registration.",
                                code="document_replaced",
                                status=409,
                            )
                    except BaseException:
                        if self._client_documents.get(client_id) is document:
                            self._forget_client_session(client_id)
                            # The new capability was never returned. Retire any
                            # partially cleaned RuntimeLoop identity through
                            # the existing bounded full-disconnect path.
                            self._schedule_disconnect_after_grace(client_id)
                        raise
                self._schedule_disconnect_after_grace(client_id, initial=True)
                if client_id == claimed_client_id:
                    intent_generation_floor = await asyncio.to_thread(
                        self._ports.document_intent_generation_floor,
                        client_id,
                    )
                    floor_read = True
        else:
            self._require_active_session(session)
            client_id, document, duplicate, _reissued = self._register_client_document(
                session,
                claimed_client_id="",
                incarnation_id=incarnation_id,
            )
            self._schedule_disconnect_after_grace(client_id, initial=True)
        if not floor_read:
            async with self._client_operation(client_id):
                self._require_active_session(session)
                if self._client_documents.get(client_id) is not document:
                    raise WebRuntimeError(
                        "This browser document was replaced during registration.",
                        code="document_replaced",
                        status=409,
                    )
                intent_generation_floor = await asyncio.to_thread(
                    self._ports.document_intent_generation_floor,
                    client_id,
                )
        return web.json_response(
            {
                "client_id": client_id,
                "document_token": document.document_token,
                "document_receipt": document.document_receipt,
                "duplicate": duplicate,
                "intent_generation_floor": intent_generation_floor,
                "csrf_token": session.csrf_token,
                **self._projection.coordinates(),
            }
        )

    async def _handle_meta(self, request: web.Request) -> web.Response:
        session = self._request_admission.session(request)
        client_id = self._required_client_id(request)
        payload = await self._document_request_to_thread(
            self._ports.meta,
            request,
            client_id,
        )
        return web.json_response({**payload, "csrf_token": session.csrf_token})

    def _require_update_port(self, name: str) -> Callable[..., dict[str, Any]]:
        port = getattr(self._ports, name, None)
        if not callable(port):
            raise WebRuntimeError(
                "当前 Focus 安装不支持浏览器更新。",
                code="update_unavailable",
                status=503,
            )
        return port

    async def _call_update_port(
        self,
        name: str,
        request: web.Request,
        client_id: str,
        *args: Any,
    ) -> dict[str, Any]:
        try:
            return await self._document_request_to_thread(
                self._require_update_port(name),
                request,
                client_id,
                *args,
                pass_client_id=False,
            )
        except FocusUpdateError as exc:
            raise WebRuntimeError(
                str(exc),
                code="update_rejected",
                status=409,
            ) from exc

    async def _handle_update_status(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        payload = await self._call_update_port("update_status", request, client_id)
        return web.json_response(payload, headers={"Cache-Control": "no-store"})

    async def _handle_update_source(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        url, confirmation = request_decoder.decode_update_source_request(body)
        payload = await self._call_update_port(
            "update_source", request, client_id, url, confirmation
        )
        return web.json_response(payload, headers={"Cache-Control": "no-store"})

    async def _handle_update_check(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        target, commit = request_decoder.decode_update_check_request(body)
        payload = await self._call_update_port("update_check", request, client_id, target, commit)
        return web.json_response(payload, headers={"Cache-Control": "no-store"})

    async def _handle_update_apply(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        operation_id, confirmation = request_decoder.decode_update_apply_request(body)
        payload = await self._call_update_port(
            "update_apply", request, client_id, operation_id, confirmation
        )
        return web.json_response(payload, headers={"Cache-Control": "no-store"})

    async def _handle_operator_status(self, request: web.Request) -> web.Response:
        # Require the current browser-document capability just like /api/meta,
        # but do not serialize this diagnostic read behind RuntimeLoop.  Both
        # RuntimeLoop.snapshot and OperationalWarningRegistry.snapshot are
        # explicitly thread-safe, so the default executor is the intended
        # observation path.
        self._required_client_id(request)
        payload = await asyncio.to_thread(self._ports.operator_status)
        return web.json_response(
            payload,
            headers={"Cache-Control": "no-store"},
        )

    async def _handle_backend_reset_preview(
        self,
        request: web.Request,
    ) -> web.Response:
        client_id = self._required_client_id(request)
        payload = await self._document_request_to_thread(
            self._ports.backend_reset_preview,
            request,
            client_id,
            pass_client_id=False,
        )
        return web.json_response(payload, headers={"Cache-Control": "no-store"})

    async def _handle_backend_reset_execute(
        self,
        request: web.Request,
    ) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        force, expected_generation = request_decoder.decode_backend_reset_request(body)
        try:
            payload = await self._document_request_to_thread(
                self._ports.backend_reset_execute,
                request,
                client_id,
                pass_client_id=False,
                force=force,
                expected_connection_generation=expected_generation,
            )
        except BackendResetKnownNoEffectError as exc:
            if isinstance(exc, BackendResetGenerationStaleError):
                code = "backend_reset_stale"
            elif isinstance(exc, BackendResetPolicyRejectedError):
                code = "backend_reset_policy_changed"
            else:
                code = "backend_reset_unavailable"
            raise WebRuntimeError(
                "Backend reset was not started; refresh the preview before trying again.",
                code=code,
                status=409,
            ) from exc
        return web.json_response(payload, headers={"Cache-Control": "no-store"})

    async def _handle_profile_update(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.update_profile,
                request,
                client_id,
                body,
                intent_generation=request_decoder.decode_intent_generation(
                    request.headers.get(_INTENT_HEADER, "")
                ),
            )
        )

    async def _handle_next_turn_settings_read(
        self,
        request: web.Request,
    ) -> web.Response:
        client_id = self._required_client_id(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.next_turn_settings,
                request,
                client_id,
                pass_client_id=False,
            ),
            headers={"Cache-Control": "no-store"},
        )

    async def _handle_next_turn_settings_update(
        self,
        request: web.Request,
    ) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.update_next_turn_settings,
                request,
                client_id,
                body,
            ),
            headers={"Cache-Control": "no-store"},
        )

    async def _handle_attachment_upload(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        if not request.content_type.startswith("multipart/"):
            raise WebRuntimeError(
                "Attachment upload must use multipart/form-data.",
                code="invalid_attachment",
            )
        reader = await request.multipart()
        thread_id = ""
        cwd = ""
        scope_generation = 0
        display_name = ""
        media_type = "application/octet-stream"
        content = bytearray()
        file_seen = False
        while True:
            field = await reader.next()
            if field is None:
                break
            if field.name == "file":
                if file_seen:
                    raise WebRuntimeError(
                        "Only one file can be uploaded per request.",
                        code="invalid_attachment",
                    )
                file_seen = True
                display_name = str(field.filename or "attachment")
                media_type = str(
                    field.headers.get("Content-Type", "") or "application/octet-stream"
                )
                while True:
                    chunk = await field.read_chunk(size=256 * 1024)
                    if not chunk:
                        break
                    content.extend(chunk)
                    if len(content) > _MAX_ATTACHMENT_BYTES:
                        raise WebRuntimeError(
                            f"Attachment exceeds the {_MAX_ATTACHMENT_BYTES}-byte limit.",
                            code="invalid_attachment",
                            status=413,
                        )
                continue
            value = (await field.text()).strip()
            if field.name == "thread_id":
                thread_id = value
            elif field.name == "cwd":
                cwd = value
            elif field.name == "scope_generation":
                try:
                    scope_generation = int(value)
                except ValueError as exc:
                    raise WebRuntimeError(
                        "Attachment scope generation must be an integer.",
                        code="invalid_attachment_scope",
                    ) from exc
        if not file_seen:
            raise WebRuntimeError(
                "Attachment upload is missing file content.", code="invalid_attachment"
            )
        result = await self._document_request_to_thread(
            self._ports.stage_attachment,
            request,
            client_id,
            thread_id=thread_id,
            cwd=cwd,
            scope_generation=scope_generation,
            display_name=display_name,
            media_type=media_type,
            content=bytes(content),
        )
        return web.json_response(result)

    async def _handle_attachment_download(
        self, request: web.Request
    ) -> web.StreamResponse:
        download = await asyncio.to_thread(
            self._ports.attachment_download,
            request.match_info["attachment_id"],
        )
        record = download.record
        media_type = str(record.media_type or "").lower()
        # Keep this narrow even if a port implementation regresses: this
        # cookie-authenticated route is a controlled image loader, not a
        # generic attachment download endpoint.
        if media_type not in _SAFE_INLINE_IMAGE_TYPES:
            raise WebRuntimeError(
                "Only verified image attachments can be rendered in Focus Web.",
                code="attachment_preview_unavailable",
                status=404,
            )
        response = web.Response(body=download.content)
        response.content_type = record.media_type or "application/octet-stream"
        response.headers["Content-Disposition"] = (
            f"inline; filename*=UTF-8''{quote(str(record.display_name), safe='')}"
        )
        response.headers["Cache-Control"] = "private, max-age=300"
        return response

    async def _handle_threads(self, request: web.Request) -> web.Response:
        client_id = self._optional_client_id(request)
        search = str(request.query.get("search", "") or "").strip()
        scope = str(request.query.get("scope", "global") or "global").strip()
        archived = str(request.query.get("archived", "") or "").strip().lower() in {
            "1",
            "true",
            "yes",
        }
        all_for_search = str(
            request.query.get("all_for_search", "") or ""
        ).strip().lower() in {
            "1",
            "true",
            "yes",
        }
        # Document-bound inventory shares the exact prepare linearization point.
        if client_id:
            result = await self._staged_document_request_to_thread(
                self._ports.prepare_list_threads,
                request,
                client_id,
                pass_client_id=False,
                client_id=client_id,
                search=search,
                scope=scope,
                archived=archived,
                all_for_search=all_for_search,
            )
        else:
            prepared = await self._external_transactions.prepare(
                self._ports.prepare_list_threads,
                client_id="",
                search=search,
                scope=scope,
                archived=archived,
                all_for_search=all_for_search,
            )
            result = await self._external_transactions.execute(
                prepared,
                self._ports.run_prepared_thread_read,
            )
        return self._json_response(result)

    async def _handle_thread(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        thread_id = request.match_info["thread_id"]
        turn_limit = request_decoder.decode_turn_window_limit(request.query)
        return self._json_response(
            await self._staged_document_request_to_thread(
                self._ports.prepare_read_thread,
                request,
                client_id,
                thread_id,
                turn_limit=turn_limit,
                intent_generation=request_decoder.decode_intent_generation(
                    request.headers.get(_INTENT_HEADER, "")
                ),
            )
        )

    async def _handle_thread_turns(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        thread_id = request.match_info["thread_id"]
        cursor = str(request.query.get("cursor", "") or "").strip()
        items_view = str(request.query.get("items_view", "full") or "").strip()
        turn_limit = request_decoder.decode_turn_window_limit(request.query)
        if items_view not in {"summary", "full"}:
            raise WebRuntimeError(
                "History items view must be 'summary' or 'full'.",
                code="invalid_items_view",
            )
        return self._json_response(
            await self._staged_document_request_to_thread(
                self._ports.prepare_list_older_turns,
                request,
                client_id,
                thread_id,
                cursor=cursor,
                items_view=items_view,
                turn_limit=turn_limit,
            )
        )

    async def _handle_thread_summary_export(
        self,
        request: web.Request,
    ) -> web.Response:
        client_id = self._required_client_id(request)
        markdown = await self._staged_document_request_to_thread(
            self._ports.prepare_export_thread_summary,
            request,
            client_id,
            request.match_info["thread_id"],
            execute=self._ports.run_prepared_thread_summary_export,
        )
        if not isinstance(markdown, bytes):
            raise WebRuntimeError(
                "Focus produced an invalid Q&A Markdown export.",
                code="thread_summary_export_protocol_error",
                status=502,
            )
        return web.Response(
            body=markdown,
            headers={
                "Cache-Control": "no-store",
                "Content-Disposition": f'attachment; filename="{SUMMARY_EXPORT_FILENAME}"',
                "Content-Type": "text/markdown; charset=utf-8",
            },
        )

    async def _handle_thread_data_export(
        self,
        request: web.Request,
    ) -> web.Response:
        client_id = self._required_client_id(request)
        data = await self._staged_document_request_to_thread(
            self._ports.prepare_export_thread_data,
            request,
            client_id,
            request.match_info["thread_id"],
            execute=self._ports.run_prepared_thread_data_export,
        )
        if not isinstance(data, bytes):
            raise WebRuntimeError(
                "Focus produced an invalid thread data export.",
                code="thread_data_export_protocol_error",
                status=502,
            )
        return web.Response(
            body=data,
            headers={
                "Cache-Control": "no-store",
                "Content-Disposition": (
                    f'attachment; filename="{THREAD_DATA_EXPORT_FILENAME}"'
                ),
                "Content-Type": "application/x-ndjson; charset=utf-8",
            },
        )

    async def _handle_start_thread(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.start_thread,
                request,
                client_id,
                text=str(body.get("text", "") or ""),
                cwd=str(body.get("cwd", "") or ""),
                attachment_ids=request_decoder.decode_attachment_ids(body),
                intent_generation=request_decoder.decode_intent_generation(
                    request.headers.get(_INTENT_HEADER, "")
                ),
            )
        )

    async def _handle_prompt(self, request: web.Request) -> web.Response:
        client_id, _request_document_receipt = self._required_client_document(request)
        body = await request_decoder.decode_json_object(request)
        expected_fields = {
            "text",
            "attachment_ids",
            "mutation_id",
            "source_scope_generation",
            "source_attachment_scope",
            "source_composer_scope_id",
        }
        if set(body) != expected_fields:
            raise WebRuntimeError(
                "A prompt submission requires one exact single-request body.",
                code="invalid_prompt",
                status=400,
            )
        mutation_id = body.get("mutation_id")
        if not is_web_mutation_id(mutation_id):
            raise WebRuntimeError(
                "Prompt mutation_id must be one canonical UUID.",
                code="invalid_mutation_id",
                status=400,
            )
        text = body.get("text")
        source_attachment_scope = body.get("source_attachment_scope")
        source_composer_scope_id = body.get("source_composer_scope_id")
        if not isinstance(text, str):
            raise WebRuntimeError(
                "Prompt text must be a string.",
                code="invalid_prompt",
                status=400,
            )
        if not all(
            request_decoder.is_exact_text(value)
            for value in (source_attachment_scope, source_composer_scope_id)
        ):
            raise WebRuntimeError(
                "Prompt source-scope fields must be exact non-empty strings.",
                code="invalid_submission_scope",
                status=400,
            )
        return web.json_response(
            await self._staged_document_request_to_thread(
                self._ports.prepare_prompt,
                request,
                client_id,
                request.match_info["thread_id"],
                execute=self._ports.run_prepared_prompt,
                transactions=self._prompt_transactions,
                text=text,
                attachment_ids=request_decoder.decode_attachment_ids(body),
                mutation_id=mutation_id,
                source_scope_generation=request_decoder.decode_safe_integer_field(
                    body,
                    "source_scope_generation",
                    positive=True,
                ),
                source_attachment_scope=source_attachment_scope,
                source_composer_scope_id=source_composer_scope_id,
            )
        )

    async def _handle_prompt_result(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        mutation_id = request.match_info["mutation_id"]
        if not is_web_mutation_id(mutation_id):
            raise WebRuntimeError(
                "Prompt mutation_id must be one canonical UUID.",
                code="invalid_mutation_id",
                status=400,
            )
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.prompt_result,
                request,
                client_id,
                request.match_info["thread_id"],
                mutation_id=mutation_id,
            )
        )

    async def _handle_interrupt(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        if set(body) != {"turn_id"}:
            raise WebRuntimeError(
                "Interrupt requires exactly one turn_id field.",
                code="invalid_turn_id",
                status=400,
            )
        turn_id = body.get("turn_id")
        if not isinstance(turn_id, str) or turn_id != turn_id.strip():
            raise WebRuntimeError(
                "Interrupt turn_id must be empty or an exact string without surrounding whitespace.",
                code="invalid_turn_id",
                status=400,
            )
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.interrupt,
                request,
                client_id,
                request.match_info["thread_id"],
                turn_id=turn_id,
            )
        )

    async def _handle_unknown_mutation(self, request: web.Request) -> web.Response:
        body = await request_decoder.decode_json_object(request)
        client_id = self._required_client_id(request)
        if set(body) != {"action", "mutation_id"}:
            raise WebRuntimeError(
                "Unknown mutation settlement contains unsupported fields.",
                code="invalid_unknown_resolution",
                status=400,
            )
        mutation_id = body.get("mutation_id")
        if not isinstance(mutation_id, str) or not mutation_id.strip():
            raise WebRuntimeError(
                "Unknown mutation settlement requires an exact mutation id.",
                code="invalid_mutation_id",
                status=400,
            )
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.resolve_unknown_mutation,
                request,
                client_id,
                request.match_info["thread_id"],
                action=str(body.get("action", "") or ""),
                mutation_id=mutation_id.strip(),
            )
        )

    async def _handle_rename_thread(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.rename_thread,
                request,
                client_id,
                request.match_info["thread_id"],
                name=str(body.get("name", "") or ""),
            )
        )

    async def _handle_compact_thread(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.compact_thread,
                request,
                client_id,
                request.match_info["thread_id"],
            )
        )

    async def _handle_review(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        target = body.get("target") if isinstance(body.get("target"), dict) else {}
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.start_review,
                request,
                client_id,
                request.match_info["thread_id"],
                target=target,
            )
        )

    async def _handle_goal(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.goal,
                request,
                client_id,
                request.match_info["thread_id"],
            )
        )

    async def _handle_set_goal(self, request: web.Request) -> web.Response:
        body = await request_decoder.decode_json_object(request)
        client_id = self._required_client_id(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.set_goal,
                request,
                client_id,
                request.match_info["thread_id"],
                objective=None
                if body.get("objective") is None
                else str(body.get("objective")),
                status=None if body.get("status") is None else str(body.get("status")),
                intent_generation=request_decoder.decode_intent_generation(
                    request.headers.get(_INTENT_HEADER, "")
                ),
            )
        )

    async def _handle_clear_goal(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.clear_goal,
                request,
                client_id,
                request.match_info["thread_id"],
                intent_generation=request_decoder.decode_intent_generation(
                    request.headers.get(_INTENT_HEADER, "")
                ),
            )
        )

    async def _handle_archive_thread(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.archive_thread,
                request,
                client_id,
                request.match_info["thread_id"],
            )
        )

    async def _handle_unarchive_thread(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.unarchive_thread,
                request,
                client_id,
                request.match_info["thread_id"],
            )
        )

    async def _handle_delete_thread(self, request: web.Request) -> web.Response:
        body = await request_decoder.decode_json_object(request)
        client_id = self._required_client_id(request)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.delete_thread,
                request,
                client_id,
                request.match_info["thread_id"],
                confirmation=str(body.get("confirmation", "") or ""),
            )
        )

    async def _handle_request_response(self, request: web.Request) -> web.Response:
        client_id = self._required_client_id(request)
        body = await request_decoder.decode_json_object(request)
        answers = body.get("answers") if isinstance(body.get("answers"), dict) else {}
        connection_generation = request_decoder.decode_request_connection_generation(
            body
        )
        response_capability = request_decoder.decode_request_response_capability(body)
        return web.json_response(
            await self._document_request_to_thread(
                self._ports.respond_request,
                request,
                client_id,
                request.match_info["request_id"],
                connection_generation=connection_generation,
                response_capability=response_capability,
                action=str(body.get("action", "") or ""),
                answers=answers,
            )
        )

    async def _handle_events(self, request: web.Request) -> web.StreamResponse:
        session = self._request_admission.session(request)
        client_id = self._query_client_id(request)
        csrf_token = str(request.query.get("csrf", "") or "").strip()
        self._request_admission.validate_websocket_csrf(session, csrf_token)
        self._request_admission.validate_origin(request)
        socket = web.WebSocketResponse(heartbeat=30.0, max_msg_size=1024 * 1024)
        sender_state = _SocketSenderState(
            queue=asyncio.Queue(maxsize=max(int(self._config.event_queue_limit), 1)),
        )
        external_reservation = False
        if session.audience.kind == "external":
            self._reserve_external_socket(session.session_token)
            external_reservation = True
        admitted = False
        rejection: WebRuntimeError | None = None
        try:
            await socket.prepare(request)
            async with self._client_operation(client_id):
                try:
                    # ``prepare`` is an await boundary. Registration may have
                    # rotated this document while the HTTP upgrade was in
                    # flight, so exact capability admission is rechecked
                    # before this socket becomes lifecycle evidence.
                    self._query_client_id(request)
                except WebRuntimeError as exc:
                    rejection = exc
                else:
                    disconnect_task = self._disconnect_tasks.pop(client_id, None)
                    if disconnect_task is not None:
                        disconnect_task.cancel()
                    self._socket_senders[socket] = sender_state
                    self._websockets.setdefault(client_id, set()).add(socket)
                    if external_reservation:
                        self._release_external_socket_reservation(session.session_token)
                        external_reservation = False
                    self._session_sockets.setdefault(
                        session.session_token,
                        set(),
                    ).add(socket)
                    self._socket_clients[socket] = client_id
                    admitted = True
                    await asyncio.to_thread(self._ports.client_connected, client_id)
            if rejection is not None:
                await socket.close(
                    code=4001 if rejection.status == 401 else 4003,
                    message=(
                        b"Focus Web session expired"
                        if rejection.status == 401
                        else b"Focus Web document was replaced"
                    ),
                )
                return socket
            await socket.send_json(
                {
                    "type": require_focus_web_event_type("hello"),
                    **self._projection.coordinates(),
                }
            )
            sender_state.task = asyncio.create_task(
                self._run_socket_sender(socket, sender_state)
            )
            async for message in socket:
                if message.type == WSMsgType.TEXT and message.data == "ping":
                    await socket.send_str("pong")
                elif message.type == WSMsgType.ERROR:
                    break
        finally:
            if external_reservation:
                self._release_external_socket_reservation(session.session_token)
            if admitted:
                async with self._client_operation(client_id):
                    self._remove_socket_sender(socket)
                    self._socket_clients.pop(socket, None)
                    session_group = self._session_sockets.get(session.session_token)
                    if session_group is not None:
                        session_group.discard(socket)
                        if not session_group:
                            self._session_sockets.pop(session.session_token, None)
                            self._maybe_cancel_session_expiry(session.session_token)
                    group = self._websockets.get(client_id)
                    if group is not None:
                        group.discard(socket)
                        if not group:
                            self._websockets.pop(client_id, None)
                            await asyncio.to_thread(
                                self._ports.client_transport_disconnected,
                                client_id,
                            )
                            self._schedule_disconnect_after_grace(client_id)
        return socket

    async def _expire_session_after(self, session: WebAuthSession) -> None:
        try:
            deadline = session.expires_at
            while True:
                await asyncio.sleep(max(deadline - time.time(), 0.0))
                current = self._auth.expire_if_due(session.session_token)
                if current is not None:
                    deadline = current.expires_at
                    continue
                await self._close_session_sockets(
                    session.session_token,
                    event_type="session_expired",
                    close_message=b"Focus Web session expired",
                )
                return
        except asyncio.CancelledError:
            return
        finally:
            current = self._session_expiry_tasks.get(session.session_token)
            if current is asyncio.current_task():
                self._session_expiry_tasks.pop(session.session_token, None)

    async def _close_session_sockets(
        self,
        session_token: str,
        *,
        event_type: str,
        close_message: bytes,
    ) -> None:
        event_type = require_focus_web_event_type(event_type)
        expiry_task = self._session_expiry_tasks.pop(session_token, None)
        if expiry_task is not None and expiry_task is not asyncio.current_task():
            expiry_task.cancel()
        sockets = tuple(self._session_sockets.pop(session_token, set()))
        affected_clients = set(self._session_clients.pop(session_token, set()))
        affected_clients.update(
            client_id
            for client_id, document in self._client_documents.items()
            if document.session_token == session_token
        )
        for socket in sockets:
            self._remove_socket_sender(socket)
            client_id = self._socket_clients.pop(socket, "")
            if client_id:
                affected_clients.add(client_id)
                group = self._websockets.get(client_id)
                if group is not None:
                    group.discard(socket)
                    if not group:
                        self._websockets.pop(client_id, None)
            if not socket.closed:
                try:
                    await socket.send_json(
                        {"type": event_type, **self._projection.coordinates()}
                    )
                except Exception:
                    logger.debug(
                        "Focus Web session close event delivery failed", exc_info=True
                    )
                await socket.close(code=4001, message=close_message)
        for client_id in sorted(affected_clients):
            if self._client_sessions.get(client_id) == session_token:
                self._client_sessions.pop(client_id, None)
            document = self._client_documents.get(client_id)
            if document is not None and document.session_token == session_token:
                self._client_documents.pop(client_id, None)
            if client_id in self._websockets:
                continue
            disconnect_task = self._disconnect_tasks.pop(client_id, None)
            if disconnect_task is not None:
                disconnect_task.cancel()
            async with self._client_operation(client_id):
                await asyncio.to_thread(self._ports.client_disconnected, client_id)

    async def _disconnect_after_grace(
        self,
        client_id: str,
        expected_document: _ClientDocument | None,
    ) -> None:
        try:
            await asyncio.sleep(max(float(self._config.disconnect_grace_seconds), 0.0))
            async with self._client_operation(client_id):
                if client_id in self._websockets:
                    return
                if (
                    expected_document is not None
                    and self._client_documents.get(client_id) is not expected_document
                ):
                    return
                await asyncio.to_thread(self._ports.client_disconnected, client_id)
                if (
                    expected_document is None
                    or self._client_documents.get(client_id) is expected_document
                ):
                    self._forget_client_session(client_id)
        except asyncio.CancelledError:
            return
        finally:
            current = self._disconnect_tasks.get(client_id)
            if current is asyncio.current_task():
                self._disconnect_tasks.pop(client_id, None)
            self._maybe_release_client_operation_lock(client_id)

    def _schedule_disconnect_after_grace(
        self,
        client_id: str,
        *,
        initial: bool = False,
    ) -> None:
        """Bound a registered document that has no active event socket.

        Registration happens before the SPA opens its WebSocket.  Giving that
        short window the same bounded grace avoids a stale, HTTP-only document
        keeping a resume hint (or a writer identity) alive until session expiry.
        A connected socket always cancels the task in ``_handle_events``.
        """

        # ``0`` deliberately means no reconnect grace after a socket closes.
        # Do not turn that setting into a race between initial registration and
        # the SPA's first ``/api/meta`` / WebSocket handshake.
        if initial and float(self._config.disconnect_grace_seconds) <= 0:
            return
        if client_id in self._websockets or client_id in self._disconnect_tasks:
            return
        expected_document = self._client_documents.get(client_id)
        self._disconnect_tasks[client_id] = asyncio.create_task(
            self._disconnect_after_grace(client_id, expected_document)
        )

    async def _handle_static(self, request: web.Request) -> web.StreamResponse:
        path = str(request.match_info.get("path", "") or "").strip("/")
        static_dir = self._static_dir().resolve()
        target = (static_dir / (path or "index.html")).resolve()
        try:
            target.relative_to(static_dir)
        except ValueError:
            raise web.HTTPNotFound()
        if not target.is_file():
            if "." in pathlib.PurePosixPath(path).name:
                raise web.HTTPNotFound()
            target = static_dir / "index.html"
        content_type, _encoding = mimetypes.guess_type(target.name)
        response = web.FileResponse(target)
        if content_type:
            response.content_type = content_type
        if target.name in _STATIC_NO_STORE_FILENAMES:
            response.headers["Cache-Control"] = "no-store"
        else:
            response.headers["Cache-Control"] = "public, max-age=31536000, immutable"
        return response

    def _on_projection_event(self, event: dict[str, Any]) -> None:
        loop = self._loop
        if loop is None or not loop.is_running():
            return
        payload = dict(event)
        loop.call_soon_threadsafe(self._enqueue_projection_event, payload)

    async def _document_request_to_thread(
        self,
        function: Callable[..., Any],
        request: web.Request,
        lock_client_id: str,
        *args: Any,
        pass_client_id: bool = True,
        **kwargs: Any,
    ) -> Any:
        """Dispatch one exact document request at its lifecycle linearization point.

        Parsing JSON or multipart bodies is an await boundary, and an already
        queued request may also wait behind another client operation.  Recheck
        the request's exact token and active session while holding the same
        lock as document reissue, socket admission, and retirement.  Stable
        client id alone is never authority to dispatch a replaced document.
        """

        async with self._client_operation(lock_client_id) as normalized_client_id:
            verified_client_id = self._required_client_id(request)
            if verified_client_id != normalized_client_id:
                raise WebRuntimeError(
                    "This browser document no longer owns the requested client id.",
                    code="document_replaced",
                    status=409,
                )
            call_args = (normalized_client_id, *args) if pass_client_id else args
            return await asyncio.to_thread(function, *call_args, **kwargs)

    async def _staged_document_request_to_thread(
        self,
        prepare: Callable[..., Any],
        request: web.Request,
        lock_client_id: str,
        *args: Any,
        pass_client_id: bool = True,
        execute: Callable[[Any], Any] | None = None,
        transactions: WebGatewayExternalTransactionRunner | None = None,
        **kwargs: Any,
    ) -> Any:
        """Prepare under the document lock, then release it before slow I/O.

        The independent prepare task owns the lock through worker completion.
        A cancelled handler therefore cannot let document replacement overtake
        a still-running prepare callback; its exact receipt is abandoned when
        that task eventually returns instead.
        """

        async def prepare_under_document_lock() -> Any:
            async with self._client_operation(lock_client_id) as normalized_client_id:
                verified_client_id = self._required_client_id(request)
                if verified_client_id != normalized_client_id:
                    raise WebRuntimeError(
                        "This browser document no longer owns the requested client id.",
                        code="document_replaced",
                        status=409,
                    )
                call_args = (
                    (normalized_client_id, *args) if pass_client_id else args
                )
                return await asyncio.to_thread(prepare, *call_args, **kwargs)

        transaction_runner = transactions or self._external_transactions
        prepared = await transaction_runner.prepare_async(
            prepare_under_document_lock
        )
        return await transaction_runner.execute(
            prepared,
            execute or self._ports.run_prepared_thread_read,
        )

    @asynccontextmanager
    async def _client_operation(self, client_id: str) -> AsyncIterator[str]:
        """Linearize one client's HTTP, socket, registration, and retirement."""

        normalized_client_id = str(client_id or "").strip()
        if not normalized_client_id:
            raise WebRuntimeError(
                "A valid browser client id is required.",
                code="invalid_client",
            )
        lock = self._client_operation_locks.setdefault(
            normalized_client_id,
            asyncio.Lock(),
        )
        self._client_operation_lock_users[normalized_client_id] = (
            self._client_operation_lock_users.get(normalized_client_id, 0) + 1
        )
        try:
            async with lock:
                yield normalized_client_id
        finally:
            users = self._client_operation_lock_users.get(normalized_client_id, 1) - 1
            if users > 0:
                self._client_operation_lock_users[normalized_client_id] = users
            else:
                self._client_operation_lock_users.pop(normalized_client_id, None)
            self._maybe_release_client_operation_lock(normalized_client_id)

    def _maybe_release_client_operation_lock(self, client_id: str) -> None:
        """Drop event-loop bookkeeping after a document leaves the Gateway."""

        if self._client_operation_lock_users.get(client_id, 0) > 0:
            return
        if (
            client_id not in self._client_sessions
            and client_id not in self._websockets
            and client_id not in self._disconnect_tasks
        ):
            self._client_operation_locks.pop(client_id, None)

    def _enqueue_projection_event(self, event: dict[str, Any]) -> None:
        for socket, state in tuple(self._socket_senders.items()):
            if socket.closed or state.overflowed:
                continue
            try:
                state.queue.put_nowait(dict(event))
            except asyncio.QueueFull:
                while True:
                    try:
                        state.queue.get_nowait()
                    except asyncio.QueueEmpty:
                        break
                state.overflowed = True
                invalidation = {
                    **event,
                    "type": require_focus_web_event_type("projection_invalidated"),
                    "thread_id": "",
                    "reason": "socket_backpressure",
                    "detail": {"reload": True},
                }
                state.queue.put_nowait(invalidation)

    async def _run_socket_sender(
        self,
        socket: web.WebSocketResponse,
        state: _SocketSenderState,
    ) -> None:
        try:
            while not socket.closed:
                event = await state.queue.get()
                await socket.send_json(event)
                if event.get("type") == "projection_invalidated":
                    state.overflowed = False
        except asyncio.CancelledError:
            return
        except Exception:
            logger.debug("Focus Web event delivery failed", exc_info=True)
            if not socket.closed:
                await socket.close(
                    code=1011, message=b"Focus Web event delivery failed"
                )

    def _remove_socket_sender(self, socket: web.WebSocketResponse) -> None:
        state = self._socket_senders.pop(socket, None)
        if state is None or state.task is None:
            return
        state.task.cancel()

    def _handle_bootstrap_rotated(self, token: str) -> None:
        if self._endpoint:
            self._save_runtime(bootstrap_token=token)

    def _save_runtime(self, *, bootstrap_token: str | None = None) -> None:
        self._runtime_store.save(
            endpoint=self._endpoint,
            bootstrap_token=bootstrap_token or self._auth.bootstrap_token,
            owner_pid=os.getpid(),
            started_at=self._started_at or time.time(),
        )

    def _clear_runtime_store_safely(self) -> None:
        """Best-effort cleanup that never hides a startup or shutdown error.

        An invalid discovery record cannot be ownership-checked, so the store
        deliberately rejects it instead of deleting it.  Gateway lifecycle
        cleanup must preserve that fail-closed evidence without replacing the
        primary lifecycle result (or preventing ``_ready`` from being set).
        """

        try:
            self._runtime_store.clear(owner_pid=os.getpid())
        except Exception:
            logger.exception(
                "无法安全清理 Focus Web Gateway runtime discovery；保留文件供诊断"
            )

    def _static_dir(self) -> pathlib.Path:
        if self._config.static_dir is not None:
            return pathlib.Path(self._config.static_dir)
        return pathlib.Path(web_assets.__file__).resolve().parent / "dist"

    def _optional_client_id(self, request: web.Request) -> str:
        client_id = str(request.headers.get(_CLIENT_HEADER, "") or "").strip()
        document_token = str(request.headers.get(_DOCUMENT_HEADER, "") or "").strip()
        if not client_id and not document_token:
            return ""
        if not client_id or not document_token:
            raise WebRuntimeError(
                "This browser document must be registered before it can use Focus Web.",
                code="document_unregistered",
                status=409,
            )
        return self._verified_document_client(
            self._request_admission.session(request),
            client_id=client_id,
            document_token=document_token,
        )

    def _required_client_id(self, request: web.Request) -> str:
        value = self._optional_client_id(request)
        if not value:
            raise WebRuntimeError("Missing browser client id.", code="invalid_client")
        return value

    def _required_client_document(self, request: web.Request) -> tuple[str, str]:
        client_id = self._required_client_id(request)
        document = self._client_documents.get(client_id)
        if document is None:
            raise WebRuntimeError(
                "This browser document is no longer registered.",
                code="document_replaced",
                status=409,
            )
        return client_id, document.document_receipt

    def _query_client_id(self, request: web.Request) -> str:
        client_id = str(request.query.get("client", "") or "").strip()
        document_token = str(request.query.get("document", "") or "").strip()
        if not client_id or not document_token:
            raise web.HTTPBadRequest(text="Missing browser document identity.")
        return self._verified_document_client(
            self._request_admission.session(request),
            client_id=client_id,
            document_token=document_token,
        )

    @staticmethod
    def _new_client_id() -> str:
        return f"web-{secrets.token_urlsafe(18)}"

    def _register_client_document(
        self,
        session: WebAuthSession,
        *,
        claimed_client_id: str,
        incarnation_id: str,
    ) -> tuple[str, _ClientDocument, bool, bool]:
        """Bind one memory-only document capability to a resumable client id.

        A live socket is the observable proof that the previous document is
        still present.  In that case a copied sessionStorage hint receives a
        new identity.  Once the old socket is gone, the same authenticated
        session may use its still-registered hint during disconnect grace; the
        old document token is rotated so it cannot continue to act. Once grace
        removes that registration, the hint is intentionally not adopted
        again: a copied browser value cannot recreate a dead document
        capability. Main-turn ownership is checked independently by the exact
        interaction lease.
        """

        existing = (
            self._client_documents.get(claimed_client_id) if claimed_client_id else None
        )
        duplicate = False
        if existing is not None:
            if (
                existing.session_token == session.session_token
                and existing.incarnation_id == incarnation_id
            ):
                self._bind_client_session(session, claimed_client_id)
                return claimed_client_id, existing, False, False
            if existing.session_token != session.session_token or bool(
                self._websockets.get(claimed_client_id)
            ):
                duplicate = True

        client_id = self._new_client_id()
        while client_id in self._client_documents or client_id in self._client_sessions:
            client_id = self._new_client_id()
        if existing is not None and not duplicate:
            client_id = claimed_client_id

        document_token = secrets.token_urlsafe(32)
        document = _ClientDocument(
            session_token=session.session_token,
            incarnation_id=incarnation_id,
            document_token=document_token,
            document_receipt=hashlib.sha256(document_token.encode("ascii")).hexdigest(),
        )
        self._client_documents[client_id] = document
        self._bind_client_session(session, client_id)
        reissued = bool(
            existing is not None and not duplicate and client_id == claimed_client_id
        )
        return client_id, document, duplicate, reissued

    def _verified_document_client(
        self,
        session: WebAuthSession,
        *,
        client_id: str,
        document_token: str,
    ) -> str:
        self._require_active_session(session)
        normalized_client_id = request_decoder.decode_client_id_hint(client_id)
        normalized_document_token = str(document_token or "").strip()
        if (
            not normalized_client_id
            or not normalized_document_token
            or len(normalized_document_token) > 256
        ):
            raise WebRuntimeError(
                "This browser document must be registered before it can use Focus Web.",
                code="document_unregistered",
                status=409,
            )
        document = self._client_documents.get(normalized_client_id)
        if (
            document is None
            or document.session_token != session.session_token
            or not secrets.compare_digest(
                document.document_token, normalized_document_token
            )
        ):
            raise WebRuntimeError(
                "This browser document was replaced or is no longer registered.",
                code="document_replaced",
                status=409,
            )
        self._bind_client_session(session, normalized_client_id)
        return normalized_client_id

    def _require_active_session(self, session: WebAuthSession) -> None:
        if self._auth.authenticate(session.session_token) is None:
            raise WebRuntimeError(
                "This Focus Web session is no longer active.",
                code="unauthorized",
                status=401,
            )

    def _reserve_external_socket(self, session_token: str) -> None:
        pending = self._external_socket_reservations.get(session_token, 0)
        session_count = len(self._session_sockets.get(session_token, ())) + pending
        total_count = sum(map(len, self._session_sockets.values())) + sum(
            self._external_socket_reservations.values()
        )
        if (
            session_count >= _MAX_EXTERNAL_SESSION_SOCKETS
            or total_count >= _MAX_EXTERNAL_SOCKETS
        ):
            raise web.HTTPTooManyRequests(
                text="Focus Web external socket limit reached."
            )
        self._external_socket_reservations[session_token] = pending + 1

    def _release_external_socket_reservation(self, session_token: str) -> None:
        pending = self._external_socket_reservations.get(session_token, 0)
        if pending <= 1:
            self._external_socket_reservations.pop(session_token, None)
        else:
            self._external_socket_reservations[session_token] = pending - 1

    def _bind_client_session(self, session: WebAuthSession, client_id: str) -> None:
        self._client_sessions[client_id] = session.session_token
        self._session_clients.setdefault(session.session_token, set()).add(client_id)
        if session.session_token not in self._session_expiry_tasks:
            self._session_expiry_tasks[session.session_token] = asyncio.create_task(
                self._expire_session_after(session)
            )

    def _forget_client_session(self, client_id: str) -> None:
        session_token = self._client_sessions.pop(client_id, "")
        if not session_token:
            return
        document = self._client_documents.get(client_id)
        if document is not None and document.session_token == session_token:
            self._client_documents.pop(client_id, None)
        clients = self._session_clients.get(session_token)
        if clients is not None:
            clients.discard(client_id)
            if not clients:
                self._session_clients.pop(session_token, None)
        self._maybe_cancel_session_expiry(session_token)

    def _maybe_cancel_session_expiry(self, session_token: str) -> None:
        if self._session_sockets.get(session_token) or self._session_clients.get(
            session_token
        ):
            return
        expiry_task = self._session_expiry_tasks.pop(session_token, None)
        if expiry_task is not None and expiry_task is not asyncio.current_task():
            expiry_task.cancel()
